training:
  batch_size: 128
  n_epochs: 10
  n_iters: 200000
  ngpu: 1
  snapshot_freq: 1000
  anneal_power: 2.0

data:
  ## mnist
  dataset: "MNIST"
  image_size: 28
  channels: 1

model:
  sigma_begin: 1
  sigma_end: 0.01
  num_classes: 10
  batch_norm: false
  ### configurations for MNIST
  ngf: 64

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
